### ISSUE TITLE
[FEATURE] Option to skip Hypothesis's flakiness detection

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1081]
**Is your feature request related to a problem? Please describe.**
Sometimes, the user wants only to run generated examples without extra network calls to verify whether the found failure is reproducible.

**Describe the solution you'd like**
Option to disable this behavior. The test should stop after the first failure.

**Additional context**
For CLI, it's about returning `True` from the error collector & setting the right outcome status. For pytest, it can be similar on the plugin-level

**Comment by kevgliss** [comment]
I also ran into this, essentially I have an entity that requires a unique field (e.g. name) schemathesis attempts to create the same entity twice. The first succeeds, but the second fails because we return a 400 status code due to the name conflict. This get's reported as flaky but is actually expected behavior. 

Resetting the server is a big lift for tests that already take quite a long time to run. 

Ideally, schemathesis would allow us to specify which endpoints should allow for status code conformance.

**Comment by Stranger6667** [comment]
Thanks for providing more context! I will try to allocate some time to work on it next week

**Comment by kevgliss** [comment]
@Stranger6667 I'm happy to create a PR for this, could you provide any guidance on how you would like it implemented?

**Comment by Stranger6667** [comment]
Cool, I was discussing this with @Zac-HD some time ago. The main idea is to store failing examples and instead of re-raising the Flaky exception, report it as a failure instead.

Here is the block to change - https://github.com/schemathesis/schemathesis/blob/7a5a8fe228577a459b12932a823559a21e5b4090/src/schemathesis/runner/impl/core.py#L302. 

I am a travelling now and hope to get back on Friday, so I can provide more info & review the code

**Comment by Stranger6667** [comment]
Resolving this, as flaky errors are reported as failures since `3.15.0`. Feel free to reopen it if, the new behavior does not solve the issue
