### ISSUE TITLE
[BUG] Shrinking for more than 5 minutes (or 500 ms)

### ISSUE THREAD

**Issue by DavidFarago** [schemathesis/schemathesis#1165]
**Describe the bug**
My test run produces multiple outputs of the following kind:
```
E           hypothesis.errors.DeadlineExceeded: Test took 514.11ms, which exceeds the deadline of 500.00ms

/home/davef/anaconda3/envs/reg/lib/python3.8/site-packages/hypothesis/core.py:568: DeadlineExceeded
------------------------------------------------------------------------------------------- Hypothesis --------------------------------------------------------------------------------------------
WARNING: Hypothesis has spent more than five minutes working to shrink a failing example, and stopped because it is making very slow progress.  When you re-run your tests, shrinking will resume and may take this long before aborting again.
PLEASE REPORT THIS if you can provide a reproducing example, so that we can improve shrinking performance for everyone.
Falsifying example: test_api(
    case=Case(body={'material': [{'id': -6.598814015355603e+16, 'quantity': -0.3333333333333333}, {'id': 0.0, 'quantity': 1.192092896e-07}, {'id': 0.0, 'quantity': -4265791994493.0}, {'id': 10000000.0, 'quantity': 2.2250738585072014e-308}, {'id': 1.5, 'quantity': 2.220446049250313e-16}, {'id': -1578167690834.0, 'quantity': 9007199254740992.0}, {'id': 1.1, 'quantity': -6.5127760395662104e+16}, {'id': 1.1, 'quantity': -3.402823466e+38}, {'id': 1.1, 'quantity': -0.5}, {'id': 2.00001, 'quantity': 2.00001}, {'id': 2.00001, 'quantity': -10000000.0}, {'id': 2.00001, 'quantity': 0.0}, {'id': 1.7976931348623157e+308, 'quantity': 2.2250738585072014e-308}, {'id': 0.5, 'quantity': 2.220446049250313e-16}, {'id': 0.5, 'quantity': 0.0}, {'id': 9007199254740992.0, 'quantity': 2.220446049250313e-16}, {'id': -37.0, 'quantity': -1.9}, {'id': 1e-05, 'quantity': -1e-05}, {'id': 2.220446049250313e-16, 'quantity': -0.3333333333333333}, {'id': -1.0, 'quantity': 3.246226244607557e+16}, {'id': 2.2250738585072014e-308, 'quantity': -10000000.0}, {'id': -282578974205985.0, 'quantity': -1.192092896e-07}, {'id': -2.00001, 'quantity': -0.3333333333333333}, {'id': -3.402823466e+38, 'quantity': -1.192092896e-07}, {'id': -0.5, 'quantity': -7.0}, {'id': -0.99999, 'quantity': -2.151672833195343e+16}, {'id': 3.402823466e+38, 'quantity': -1.175494351e-38}], 'week': '1106-W66'}),
```
So did it take more than 5 minutes or more than 500ms? 

Unfortunately, I cannot provide code as it is not open source. Can I help in any other way?

**Environment (please complete the following information):**
 - OS:  Ubuntu 19.04
  - Python version: 3.8.8
  - pytest 6.2.3
 - Schemathesis version: 3.6.4
 - Spec version: 3.0.0

**Comment by DavidFarago** [comment]
Might shrinking be slow due to https://github.com/schemathesis/schemathesis/issues/1164?

**Comment by Stranger6667** [comment]
> So did it take more than 5 minutes or more than 500ms?

One of the test executions took more than 500ms (including waiting for the server's response and performing all checks). When some failure was found, Hypothesis tried to shrink it and the overall time took more than 5 minutes for all additional test executions during the shrinking phase. Could you check whether some failure not related to `DeadlineExceeded` happened during the run? E.g., on the server-side. 

I need to check the Hypothesis's internals, but I expect that when the test only fails with `DeadlineExceeded` shrining should not happen, so there should be some actual failure under the hood.

> Unfortunately, I cannot provide code as it is not open source. Can I help in any other way?

It will be great to have some schema subset (if it is a public schema), otherwise, just response timings will be helpful.

> Might shrinking be slow due to #1164?

I think that your assumption is right! There could be other additions to the shrinking time (I need to re-check what actually counts in Hypothesis), but I think that the response time is the main suspect in this case

**Comment by DavidFarago** [comment]
With the new version that has #1164 fixed, I removed all `deadline` and `timeout` parameters and repeated the test run that led to this bug report:

I no longer get any `hypothesis.errors.DeadlineExceeded` (and I do get `requests.Timeout` exceptions that lead to `schemathesis.exceptions.CheckFailed`).

Thanks again for your quick answers and fixes.
