### ISSUE TITLE
[BUG] Schemathesis Can't handle a simple recursive reference:

### ISSUE THREAD

**Issue by fscarlato** [schemathesis/schemathesis#1611]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

I'm still getting:
hypothesis.errors.Unsatisfiable: Currently, Schemathesis can't generate data for this operation due to recursive references in the operation definition. See more information in this issue - https://github.com/schemathesis/schemathesis/issues/947

And the schema is a simple Parent-Child relationship:

    CategoryChildCreate:
      required:
        - category_id
        - category_label
      type: "object"
      properties:
        category_id:
          $ref: "#/components/schemas/CategoryId"
        category_label:
          type: "string"
        description:
          type: string
          maxLength: 255
        image:
          type: "string"
          format: "base64"
        children:
          type: array
          items:
            $ref: "#/components/schemas/CategoryChildCreate"

If this is a recursion level problem, why it isn't solved by defining a maximum depth?
Can this maximum depth be specified from the command line?

**Comment by Stranger6667** [comment]
Hi! 

I know that is long overdue and I am sorry for not getting back to you earlier. 

The underlying issue is on the `hypothesis-jsonschema` side and Schemathesis works around it by schema inlining and cutting of leaves that contain recursive references. That is quite hacky as we need to avoid over-inlining and at the same time resolve references deep enough.

It recently got a significant improvement in `3.18.0` and it should cover the schema you provided too. This approach has limitations as it does not work on references that recurse via multiple intermediate references. I am going to address it in a separate issue and close this one. 

But ideally, we'd like to rewrite `hypothesis-jsonschema` so it supports recursive references natively.

**Comment by Stranger6667** [comment]
> Can this maximum depth be specified from the command line?

Not at the moment, but I'd consider this in the new issue where I'll gather the current limitations
