### ISSUE TITLE
[QUESTION] Can I skip resolving references in the schema?

### ISSUE THREAD

**Issue by noddycode** [schemathesis/schemathesis#1666]
I'm working with a very large and _very_ deeply nested schema, something we'd like to improve once we get some basic tests in place to check our refactors. In the meantime, I've disabled the response_schema_conformance check and have been using the other checks along with some custom ones to write tests.

Profiling our current tests, I'm seeing that there is a lot of overhead in loading the schema due to the calls to InliningResolver.resolve_all (and deepcopy within that). Since I do not currently need the referenced objects (I'm building cases from scratch due to aforementioned complexity), is there a way to skip resolving references to get our tests running more quickly in the meantime?

**Comment by Stranger6667** [comment]
Hi!

At the moment I think the only way to avoid this is to modify the schema via the `before_load_schema` hook. I'd like to note that Schemathesis recently got some improvements on `deepcopy` (by using a specialized version) which may improve performance for you. 

I am skeptical about having a built-in option to skip resolving as it looks like a very specific use case that could be solved via a hook. Effectively it means dropping all references, but it is not clear what should be used instead of them. It is even more unclear as there could be cases that will become invalid if references are just dropped or replaced with a static value (e.g. merging schemas via `allOf`).

**Comment by noddycode** [comment]
I did end up resolving this with a hook, specifically using `before_process_path` to remove the content keys from all the responses. Thank you!
