### ISSUE TITLE
[FEATURE] Stateful: Only use linked data when present 

### ISSUE THREAD

**Issue by juk80x** [schemathesis/schemathesis#1669]
**Is your feature request related to a problem? Please describe.**
When testing an OpenAPI Spec that includes links, the client is also running tests using random/unlinked data. This generates a lot of tests that will always fail without the linked data. 

**Describe the solution you'd like**
There should be a way to force the scenario to only use linked data. 

**Describe alternatives you've considered**
I do not know enough about the tool to fix this. 

**Additional context**
No additional context.

**Comment by Stranger6667** [comment]
Hi @juk80x 

Thank you for opening this issue! Originally this was added in #965 to increase the variety of generated data for cases when it is not possible to generate anything (all operations require some input stateful data). However, it decreases the quality of data for other cases and I think it is indeed a bad trade-off - when it is not possible to generate anything statefully, then there will be an error and the user should try some hooks or use the stateless mode. Going to be fixed by #1679
