### ISSUE TITLE
Sending `Accept` headers based on schema definition

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1733]
I am testing an API where there is a requirement to send specific Accept headers, the team that developed this API created their own media type containing version numbers of some sort. 

When I test with Schemathesis I see that */* is sent as a value for this header for every test. The */* value sadly does not cover the value I need to send, is there any way I could change this in Schemathesis?

**Comment by Stranger6667** [comment]
Hi! Can you, please, share how such headers are represented in more detail? Are they represented in the schema?

Generally, headers can be overridden via CLI by the `-H` option or in Python tests by passing values as a dictionary in the `headers` keyword argument to `case.call`. I guess that the expected behavior would be if Schemathesis sends in `Accept` what is defined in the `content` keyword in response, right?

**Comment by Stranger6667** [comment]
@hoog1511 Please, let me know if my comment above is sufficient. If not, I'd be happy to elaborate
