### ISSUE TITLE
[BUG] Cannot import Astroid with schemathesis 3.19.6.

### ISSUE THREAD

**Issue by kain88-de** [schemathesis/schemathesis#1745]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
When I start a pytest session the astroid package enters an infinite loop when it is imported. 

**To Reproduce**
I prepared a [pipenv file](https://gist.github.com/kain88-de/be901c0962fa9b67a47dd8b5cd790ac2) that creates an environment to reproduce the issues.

Once you downloaded all files run 

1. `make .venv`
2. `run-pipenv run python -m pytest t.py --pdb`

This will drop you in a debugger session at the place where astroid is stuck in a loop. With version 3.19.0 everything still works.

**Expected behavior**

Adding schemathesis as a dependency has no impact if I can import astroid in a pytest environment or not. 

**Environment (please complete the following information):**

- OS: linux 
- Python version: 3.11
- Schemathesis version: 3.19.6

**Additional context**
I'm not sure what the root cause is so I will also open tickets for this with [pytest](https://github.com/pytest-dev/pytest/issues/11053) and [astroid](https://github.com/pylint-dev/astroid/issues/2191).

**Comment by The-Compiler** [comment]
Over in https://github.com/pytest-dev/pytest/issues/11053#issuecomment-1572518203, I bisected this to https://github.com/schemathesis/schemathesis/pull/1736 - apparently, doing something like:

```python3
from dataclasses import dataclass

print(type(__builtins__))
print(hasattr(__builtins__, "__builtins__"))

@dataclass
class Bla(Exception):

    __module__ = "builtins"

print(type(__builtins__))
print(hasattr(__builtins__, "__builtins__"))
```

causes a `__builtins__.__builtins__` to appear out of nowhere, and that in turn causes `astroid` to choke. Why? No idea! But schemathesis seems to be out of the picture, unless you want to avoid this kind of pattern to work around this. But I suppose it should be fixed in astroid.

**Comment by Stranger6667** [comment]
I think this should be fixed on the `astroid` side, going to close this one. Thank you for investigating and providing context!
