### ISSUE TITLE
[BUG] from_asgi broken for e.g. django asgi

### ISSUE THREAD

**Issue by devkral** [schemathesis/schemathesis#1752]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
There are multiple problems with the asgi_loader (potentially also with the wsgi loaders):

1. the base_url is not passed to the ASGIClient (django server name checks fail)
2. post needs the scheme in front of the relative  path and a fallback e.g. http://
3. setting the ip address to "testclient" can break ratelimitting stuff, an overwrite would be nice
4. in the docs there are sometimes the misspelling of from_asgi as from_wsgi at least at the navigation sidebar level. It is very confusing, because from_wsgi exists too

**To Reproduce**

look into the loaders

**Expected behavior**

**Environment (please complete the following information):**

- OS: linux
- Python version:3.11
- Schemathesis version: [e.g. 2.4.1]
- Spec version: [e.g. Open API 3.0.2]

**Additional context**

**Comment by devkral** [comment]
added the problem with the missspelling of asgi

**Comment by Stranger6667** [comment]
> the base_url is not passed to the ASGIClient (django server name checks fail)

Could you tell me more about the Django check you mentioned? Where can I find this check?
Otherwise, we join the path with URL itself within e.g. `as_requests_kwargs` so we have the full URL and it is expected to work as needed, however, I might be missing some usage scenarios here beyond what we have in our test suite.

> post needs the scheme in front of the relative path and a fallback e.g. http://

In what circumstances do we miss some details like the ones you mention? I am not completely sure what you mean by that

> setting the ip address to "testclient" can break ratelimitting stuff, an overwrite would be nice

IP address of what exactly? I only see that `testclient` is used in the `User-Agent` header - if it is what you meant, then there is the `headers` argument to `call_asgi` which will override this. It is also not clear to me in what context you use Schemathesis, is it in Python tests, or in CLI or some custom integration on top of the core engine?

> in the docs there are sometimes the misspelling of from_asgi as from_wsgi at least at the navigation sidebar level. It is very confusing, because from_wsgi exists too

Right, I am planning to rework the whole WSGI / ASGI section to avoid this.

**Comment by devkral** [comment]
- the base_url problem: django checks the hostname. e.g. ALLOWED_IPS = ["secretgraph.net"] can be only accessed if the hostname is secretgraph.net.
- the client ip address is set to testclient in case asgi is used (not your code but the code of starlite?). But this can be changed by passing through the client ip address. django does some plausability checking (e.g. is https, is allowed ip range) and fails here
- there is a typo in the sidebar

**Comment by Stranger6667** [comment]
I had a hard time finding the issues in the codebase, especially as the issue lacks any reproducible code samples that may demonstrate any of the mentioned problems. Even though some time has passed, I have some notes.

> the base_url problem: django checks the hostname. e.g. ALLOWED_IPS = ["secretgraph.net"] can be only accessed if the hostname is secretgraph.net.

The `base_url` has always been used in the the underlying client. The full URL is explicitly constructed inside the Schemathesis code and passed down to `starlette_testclient`. So, the end-user has control over it both in CLI & Python tests.

> the client ip address is set to testclient in case asgi is used (not your code but the code of starlite?). But this can be changed by passing through the client ip address. django does some plausability checking (e.g. is https, is allowed ip range) and fails here. So please allow to change the ip address

I don't know where does `starlette_testclient` set it and what specific checks does Django perform, but I can assume it uses i.e. the `Host` header which can be customized. Otherwise, I'd like to have more specifics on this.

> in the docs there are sometimes the misspelling of from_asgi as from_wsgi at least at the navigation sidebar level. It is very confusing, because from_wsgi exists too
> there is a typo in the sidebar

Still not seeing the concrete occurrence in the docs sidebar. There is a subsection "ASGI / WSGI support", but I don't see what typo you mean.

Feel free to re-open as you'd have some more actionable input on the issues you mentioned.
