### ISSUE TITLE
[QUESTION] Specifying ordering of tests

### ISSUE THREAD

**Issue by ravy** [schemathesis/schemathesis#2291]
question:
i have swagger 2.0 docs. links are not supported in that swagger version. 
so i can order the apis while testing using dredd hooks and custom sort function 
to specify the exact order the apis need to be tested
to achieve the same using schemathesis 
i use --hypothesis-phases=explicit with examples provided for all api, which is the test data
but i do not know how to enforce order

discussion:

i currently see two ways around this:
1. programatically introduce links in the schema after using a tool to convert docs from openapi 2.0 to 3.0
2. enforce order in schemathesis hooks

is there any schemathesis recipe/hook that can help me enforce order or openapi links is the way to go?

for example:
lets say we have 3 api on a resource named 'topic':
POST topics
DELETE topics/id
GET topics/id

and 3 api on a resource named 'subtopic' that exists under 'topic'
POST topic/id/subtopics
DELETE topic/id/subtopics/id2
GET topic/id/subtopics/id

i want to have a test case in this order exactly:
POST topics > GET topics > POST subtopics > GET subtopics > DELETE subtopics > DELETE topics

**Comment by Stranger6667** [comment]
Thanks for opening this! I'll get back to it a bit later, but meanwhile, I want to say that Schemathesis supports the `x-links` extension on Swagger 2.0 that has the same structure as `links` on Open API 3.x

**Comment by Stranger6667** [comment]
Schemathesis does not support changing the test order as of now. For an arbitrary case, it may require storing all API operations in memory which is problematic for large APIs (due to reference resolving, i.e. "methods" part could live in a different location, so it requires resolving). It could be done via a separate routine that will be called only if the order is specified explicitly. Still, I didn't find this feature important enough to increase the complexity of the codebase. I have some refactorings ongoing with all the traversing logic, so I'll re-assess it.

However, if you don't have references in path items, you can adjust the order via the `before_load_schema` hook. The trick is that Schemathesis iterates over Python dictionaries when it traverses the schema and with this hook, you can influence this order. I.e. take the value of the `paths` key and create a new dict moving path items there in the order you want:

```python
raw_schema["paths"] = {
    "/users": raw_schema["paths"]["users"],
    # ...
}
```

I think this idea can be extended to methods as well. So, with this change, Schemathesis will traverse the new dictionary and will follow the order in which you specified the keys.

But as you mentioned the operations, I see that they rely on `id`, which means they are stateful, so regular non-stateful tests will not be that effective as they don't have the information about what `id` value exists on the app side (and it will most likely lead to 404). Therefore, stateful testing via Open API links is the way to go with Schemathesis here.

**Comment by Stranger6667** [comment]
@ravy Please, let me know if the comment above was in any way helpful. If not I'd be happy to elaborate
