### ISSUE TITLE
Schema validation of basePath should permit empty string

### ISSUE THREAD

**Issue by jonahbenton** [schemathesis/schemathesis#541]
The JSON schema against which swagger defined APIs is validated requires at least a "/" to be present in the basePath key. This is as per swagger spec but from a mechanical/implementation perspective is incorrect. Code assembles URLs from scheme, host, basepath and path/routes, for APIs that start at the root, in that case the value of basePath is "", not "/", and tools that expose a spec (python's connexion for one) will generate an empty string basePath.

**Comment by Stranger6667** [comment]
By default, the schema validation is enabled and the input schemas with `basePath` as an empty string will fail. It can be disabled with `--validate-schema=false` CLI option or `validate_schema=False` option to any loader (except `from_pytest_fixture` that I missed for some reason). Let me know if it will be enough for your case

Regarding the implementation side. I guess it depends on the framework. We use `aiohttp` with `connexion` and it [rejects](https://github.com/zalando/connexion/blob/master/connexion/apps/aiohttp_app.py#L61) empty base paths. I am not sure what implementations you have in mind, could you give me an example, please?

Also, if some framework generates a schema that is not compliant to Open API specs it feels to me more like a problem on the framework side. I am not that keen to handle special cases by default on the Schemathesis side because they are not predictable and imply some extra maintenance, but we have an idea to have some fix-ups for certain frameworks like Fast API (#503 ), their case is that `pydantic` uses numeric values for `exclusiveMaximum` / `exclusiveMinimum` which is not compliant with Open API < 3.1.0 (which is in draft now)

**Comment by jonahbenton** [comment]
Thanks- yeah, would prefer to be able to leave validate schema on, but since we are regularly using other validation tools at different points in the workflow it's not a big deal. 

Interesting point re: connexion/aiohttp. We are using connexion with gevent and with the swagger UI extension, then also feeding our spec to Google Cloud's Envoy-based gateway and both are fine both with:
* a spec that lacks a basePath key altogether
* a spec that has a defined basePath of empty string, or of single slash '/'
 
Where the pain comes in wrt schemathesis is in our initial use with the cli. 

We author our spec in yaml, then give it to connexion, which makes it available under /swagger.json as part of the swagger /ui. We tell the cli to test using the *generated* swagger.json. 

The swagger.json generated by connexion's ui extension includes a blank basePath in 3 cases:

* when we don't provide a basePath key in the source
* when we provide a basePath key with an empty string value
* when we provide a basePath key with a '/' value

It may be that this latter case is a better classified as a bug in the connexion ui extension. 

In any event, we are fine with a WONTFIX and not having schemathesis validate the schema, since we have other places where that happens. Thanks again for a great project.

**Comment by Stranger6667** [comment]
As an alternative approach - we can add a special "connexion" fixup to `schemathesis.fixups` and make empty `basePath` to be accepted. Possibly, it could be done by modifying the spec definition via the `before_load_schema` hook.
