### ISSUE TITLE
AsyncAPI support

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#713]
https://www.asyncapi.com/docs/getting-started/

**Comment by vkosuri** [comment]
Any ETA? I am eager to see this feature.

**Comment by Stranger6667** [comment]
Hi @vkosuri 

It is something that I plan to add to Schemathesis.io first (at least 6+ months from now), as the feature is quite large. Let me know if you have any specific requirements on this - I'd be happy to discuss them.

**Comment by vkosuri** [comment]
Thanks @Stranger6667 

Had a question, We can check the OpenAPI specifications constrained Input structure and Response structure

In order to conformance on asyncapi it requires some checks, curious to know how to put a check because it uses publish/subscribe where publisher fire and ignore and where the testing will go? 

Some open API testable specifications
Input structure

- 200 OK responses must have a non-empty body
- 204 No Content and 205 Reset Content responses must have an empty body
- 302 Found responses to a POST request must allow the sub-sequent response to use either POST or GET methods
- 405 Method Not Allowed responses must have an Allow header listing supported methods
- 500 Internal Server Error responses are always errors
- GET fails after successful DELETE (use-after-free rule) [4]
- GET fails after an unsuccessful POST (resource-leak rule

Structure of API responses Tests

- Check response has an undeclared status code
- Check response has undeclared content-type
- Check response body matches the schema
- Check response has wrong headers or missing required headers
- Non-conforming requests are rejected (negative testing)
- No information leaks from unauthorized requests

**Comment by vkosuri** [comment]
@Stranger6667 any inputs from your side? How to go?

**Comment by Stranger6667** [comment]
> In order to conformance on asyncapi it requires some checks, curious to know how to put a check because it uses publish/subscribe where publisher fire and ignore and where the testing will go?

At the moment, there is no support for it at all. Neither for data generation nor for checks. The direction is:
- Implement a separate "Schema" class that iterates over API operations similar to [this one](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/specs/openapi/schemas.py#L781), for example, - Adjust corresponding `Case` class if AsyncAPI requires so
- Implement the transport layer you need inside this new "Case" class, including receiving some responses from the subscribers / or other components that should be checked. Not sure what are the mechanism there for such kinds of things as it is an event-driven ecosystem without a clear request-response flow.
- Then all the checks should be able to verify those "responses"

I didn't dig deep enough into the AsyncAPI spec to give more details, so I am afraid that my answer isn't much helpful :(

**Comment by Stranger6667** [comment]
Not something feasible atm
