### ISSUE TITLE
Skip deprecated endpoints in Open API tests

### ISSUE THREAD

**Issue by alex-pancho** [schemathesis/schemathesis#715]
Sometimes we can mark some point as deprecated, and leave into docs, but is point not supported
But now schemathesis call API points mark as deprecated
Should you can change this?

**Comment by Stranger6667** [comment]
Hi @alex-pancho !

Correct me if I am wrong, but basically you mean if schemathesis can skip testing deprecated endpoints?

If so, then would `--skip-deprecated-endpoints` CLI flag and `skip_deprecated_endpoints=True` argument for loaders (e.g. `from_uri(..., skip_deprecated_endpoints=True)`) work as a convenient interface for your use case?

**Comment by alex-pancho** [comment]
if i try to use command line option I got error
Error: no such option: --skip-deprecated-endpoints

**Comment by Stranger6667** [comment]
I meant it as a potential feature we can add to Schemathesis - currently, it is only on the interface design level

**Comment by Stranger6667** [comment]
For now, I want to be sure if I got your idea right, then I can implement such a feature

**Comment by alex-pancho** [comment]
Yes, you got it right, but it might be better if the deprecated points are skipped by default, and only if they need to be tested then we call --skip_deprecated_endpoints = False

**Comment by Stranger6667** [comment]
From my point of view, it would be better to keep deprecated endpoints by default because of the following reason.

Even if they are deprecated, they can contain vulnerabilities, including security ones (e.g., DDoS vectors). Having them tested by default will increase the chance of these bugs being discovered. I think that default settings should be done in the way to cover the most possibilities in a general case. And turning them off will be quite simple - with a single option, which sounds like a good trade-off to me.

Implementation notes for contributors that might want to work on this feature:

- Add `skip_deprecated_endpoints` attribute of type `bool` to `BaseSchema` and `LazySchema`
- Add `skip_deprecated_endpoints` to `parametrize` methods and pass it down to the `clone` method similar to other arguments
- In `BaseOpenAPISchema.get_all_endpoints` modify [the condition](https://github.com/schemathesis/schemathesis/blob/master/src/schemathesis/specs/openapi/schemas.py#L62) that handles skipping to skip an endpoint if it is deprecated and the `skip_deprecated_endpoints` attribute value is `True`
- Add `--skip-deprecated-endpoints` option to CLI and pass it down to the `runner` package to the schema creation
- Add a test in `test_parametrization.py`
