### ISSUE TITLE
[FEATURE] Copy-paste the pypi introduction docs to readthedocs

### ISSUE THREAD

**Issue by mdavis-xyz** [schemathesis/schemathesis#749]
**Is your feature request related to a problem? Please describe.**

I heard a friend recommend schemathesis. I only have a vague idea about what it does.

So like any good developer I went straight to [the documentation](https://schemathesis.readthedocs.io/en/stable/index.html).

There is nothing on that page that explains what schemathesis is, how to use it etc.
If I click on the first item in that table of contents it takes me to [this paragraph](https://schemathesis.readthedocs.io/en/stable/usage.html#storing-network-requests) about how to enable debug logging.

At this stage I barely know what schemathesis is, or whether I should use it. So I don't care about how to toggle a debug flag.

It turns out that all the stuff I do want to know is on [the PyPI page](https://pypi.org/project/schemathesis/).

> Schemathesis is a tool for testing your web applications built with Open API / Swagger or GraphQL specifications. ...

**Describe the solution you'd like**

Everything on [the PyPI page](https://pypi.org/project/schemathesis/) should be copy-pasted up the top of [the readthedocs home page](https://schemathesis.readthedocs.io/en/stable/index.html) directly, or added as the first item in the table of contents. 

**Describe alternatives you've considered**

Perhaps there should just be one sentence added to the top of [the readthedocs home page](https://schemathesis.readthedocs.io/en/stable/index.html) pointing new users to [the PyPI page](https://pypi.org/project/schemathesis/).

**Additional context**

As a Python user, this is the first time I have ever found a module with a substantial amount of introductory information present on PyPI but not in the documentation itself.

**Comment by Stranger6667** [comment]
Hi @mdavis-xyz 

You indeed right! the content of the README file and the readthedocs pages should be re-organized. I am taking it as a priority and will work on this during the next following days.

Related: #500

**Comment by Stranger6667** [comment]
I restructured the docs, so the documentation has an intro and moved most of the README.rst content to the docs under relevant sections - docs are updated on the Github page, PyPI, and Readthedocs. It is indeed the first step to at least avoid the user's confusion with missing usage guide - I plan to revisit the whole structure of the documentation and make it more user-friendly in the next few days.

Thank you for pointing out this problem; hopefully, this issue is solved for now. Feel free to reopen this one or create new issues if you encounter any difficulties with Schemathesis.
