### ISSUE TITLE
[BUG] Optional object fields treated as required

### ISSUE THREAD

**Issue by ysangkok** [schemathesis/schemathesis#899]
Using the schemathesis master from just now, version 2.8.4.

test.yaml:

```
openapi: 3.0.3
servers:
  - url: 'https://example.com'
info:
  title: Foobar
  version: '0.1'
paths:
  /data.json:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice:
                    type: number
          description: Foobar
```

test.py:
```
import schemathesis
from schemathesis.checks import ALL_CHECKS
schema = schemathesis.from_path('test.yaml', base_url='http://localhost:8000')
endpoint = schema['/data.json']['GET']
strategy = endpoint.as_strategy()
case = strategy.example()
resp = case.call()
case.validate_response(resp, ALL_CHECKS)
```

data.json:
```
{
    "invoice": null
}
```

Now, I start an HTTP server using `python3 -m http.server`. While the server is running, in a separate terminal, I run `python3 test.py`. It reports:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    case.validate_response(resp, ALL_CHECKS)
  File "/home/janus/.pyenv/versions/3.9.0rc2/lib/python3.9/site-packages/schemathesis/models.py", line 323, in validate_response
    raise exception_cls(
schemathesis.exceptions.CheckFailed: 

1. The received response does not conform to the defined schema!

Details: 

None is not of type 'number'

Failed validating 'type' in schema['properties']['invoice']:
    {'type': 'number'}

On instance['invoice']:
    None

----------

Response payload: `{
    "invoice": null
}
```

But I expect the program to finish with no errors, since the "invoice" field is not marked as `required` in the OpenAPI spec.

**Comment by Stranger6667** [comment]
Hi!

From what I see in the example, the behavior is correct. The given payload is invalid since it has the `null` type, but `number` is expected as it is described in the error message.

> But I expect the program to finish with no errors, since the "invoice" field is not marked as required in the OpenAPI spec.

You might want to use `type: ["number", "null"]` instead of `type: "number"` if you'd like to treat `null` as the valid `invoice` value. But from the JSON Schema (and from the Open API in this aspect) point of view, these are two different things - required only validates if all keys are present in the validated object, and `type: "null"` allows that key's value to be `null`.

From the JSON Schema [spec](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.15):

> An object instance is valid against this keyword if its property set contains all elements in this keyword's array value.

Therefore if something is not in the `required` list, then the `required` keyword validation passes, and in this example, it fails deeper.

Here are some extra examples:

For the example schema you provided:

1. `{}` - valid
2. `{"invoice": 42}` - valid
3. `{"invoice": null}` - invalid

Valid for `{"type": "object", "properties": {"invoice": {"type": ["number", "null"}}}`:

1. `{}` - valid
2. `{"invoice": 42}` - valid
3. `{"invoice": null}` - valid

For `{"type": "object", "properties": {"invoice": {"type": ["number", "null"}}, "required": ["invoice"]}`:

1. `{}` - invalid
2. `{"invoice": 42}` - valid
3. `{"invoice": null}` - valid


Let me know if this helps :) I can provide a more detailed explanation of this behavior.

**Comment by ysangkok** [comment]
Ah, great explanation. Unfortunate this means default behaviour varies between Marshmallow and Swagger. I will adjust my Marshmallow serialization to [omit None values](https://github.com/marshmallow-code/marshmallow/issues/229#issuecomment-363250656)...
